-- Full brand/model catalog seed (idempotent)
CREATE TEMP TABLE tmp_brands (
  name text NOT NULL,
  slug text NOT NULL,
  is_active boolean NOT NULL
) ON COMMIT DROP;
INSERT INTO tmp_brands (name, slug, is_active) VALUES
('Toyota','toyota',true),
('Nissan','nissan',true),
('Hyundai','hyundai',true),
('Kia','kia',true),
('Mazda','mazda',true),
('Mitsubishi','mitsubishi',true),
('Suzuki','suzuki',true),
('Honda','honda',true),
('Ford','ford',true),
('Chevrolet','chevrolet',true),
('Volkswagen','volkswagen',true),
('Renault','renault',true),
('Peugeot','peugeot',true),
('Dacia','dacia',true),
('Mercedes-Benz','mercedes-benz',true),
('BMW','bmw',true),
('Audi','audi',true),
('Isuzu','isuzu',true),
('Subaru','subaru',true),
('Land Rover','land-rover',true),
('JAC','jac',true),
('Lexus','lexus',true),
('Infiniti','infiniti',true),
('Porsche','porsche',true),
('MINI','mini',true),
('Jeep','jeep',true),
('RAM','ram',true),
('Volvo','volvo',true),
('Skoda','skoda',true),
('SEAT','seat',true),
('Cupra','cupra',true),
('Citroen','citroen',true),
('Opel','opel',true),
('Fiat','fiat',true),
('Alfa Romeo','alfa-romeo',true),
('Chery','chery',true),
('Geely','geely',true),
('BYD','byd',true),
('Great Wall','great-wall',true),
('Haval','haval',true),
('MG','mg',true),
('Tesla','tesla',true),
('Polestar','polestar',true),
('Jaguar','jaguar',true),
('Maserati','maserati',true),
('Ferrari','ferrari',true),
('Lamborghini','lamborghini',true),
('Bentley','bentley',true),
('Rolls-Royce','rolls-royce',true),
('Aston Martin','aston-martin',true),
('Bugatti','bugatti',true),
('DS','ds',true),
('SAIC','saic',true);
INSERT INTO brands ("Id", "Name", "Slug", "IsActive")
SELECT
  (
    substr(md5(tb.slug),1,8) || '-' ||
    substr(md5(tb.slug),9,4) || '-' ||
    substr(md5(tb.slug),13,4) || '-' ||
    substr(md5(tb.slug),17,4) || '-' ||
    substr(md5(tb.slug),21,12)
  )::uuid,
  tb.name,
  tb.slug,
  tb.is_active
FROM tmp_brands tb
ON CONFLICT ("Slug") DO UPDATE
SET "Name" = EXCLUDED."Name",
    "IsActive" = EXCLUDED."IsActive";
CREATE TEMP TABLE tmp_models (
  brand_slug text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  is_active boolean NOT NULL
) ON COMMIT DROP;
INSERT INTO tmp_models (brand_slug, name, slug, is_active) VALUES
('toyota','Hilux','hilux',true),
('toyota','Land Cruiser','land-cruiser',true),
('toyota','Land Cruiser Prado','land-cruiser-prado',true),
('toyota','RAV4','rav4',true),
('toyota','Corolla','corolla',true),
('toyota','Yaris','yaris',true),
('toyota','Fortuner','fortuner',true),
('toyota','Avanza','avanza',true),
('toyota','Hiace','hiace',true),
('toyota','Camry','camry',true),
('toyota','C-HR','c-hr',true),
('toyota','Rush','rush',true),
('toyota','Raize','raize',true),
('toyota','Corolla Cross','corolla-cross',true),
('toyota','Yaris Cross','yaris-cross',true),
('nissan','Navara','navara',true),
('nissan','Patrol','patrol',true),
('nissan','X-Trail','x-trail',true),
('nissan','Qashqai','qashqai',true),
('nissan','Sunny','sunny',true),
('nissan','Juke','juke',true),
('nissan','Almera','almera',true),
('nissan','Sentra','sentra',true),
('nissan','Murano','murano',true),
('nissan','Pathfinder','pathfinder',true),
('nissan','Terrano','terrano',true),
('nissan','Kicks','kicks',true),
('nissan','NP300','np300',true),
('nissan','Frontier','frontier',true),
('nissan','Urvan','urvan',true),
('hyundai','Tucson','tucson',true),
('hyundai','Santa Fe','santa-fe',true),
('hyundai','Creta','creta',true),
('hyundai','i20','i20',true),
('hyundai','Elantra','elantra',true),
('hyundai','Accent','accent',true),
('hyundai','Kona','kona',true),
('hyundai','Palisade','palisade',true),
('hyundai','Staria','staria',true),
('hyundai','H-1','h-1',true),
('hyundai','Venue','venue',true),
('hyundai','Sonata','sonata',true),
('hyundai','Grand i10','grand-i10',true),
('hyundai','ix35','ix35',true),
('hyundai','Porter','porter',true),
('kia','Sportage','sportage',true),
('kia','Sorento','sorento',true),
('kia','Picanto','picanto',true),
('kia','Seltos','seltos',true),
('kia','Rio','rio',true),
('kia','Cerato','cerato',true),
('kia','Sonet','sonet',true),
('kia','Carnival','carnival',true),
('kia','Stonic','stonic',true),
('kia','Carens','carens',true),
('kia','K5','k5',true),
('kia','Niro','niro',true),
('kia','Telluride','telluride',true),
('kia','Morning','morning',true),
('kia','Bongo','bongo',true),
('mazda','BT-50','bt-50',true),
('mazda','CX-5','cx-5',true),
('mazda','CX-3','cx-3',true),
('mazda','Mazda3','mazda3',true),
('mazda','Mazda6','mazda6',true),
('mazda','CX-30','cx-30',true),
('mazda','CX-9','cx-9',true),
('mazda','CX-60','cx-60',true),
('mazda','2','2',true),
('mazda','5','5',true),
('mazda','CX-50','cx-50',true),
('mazda','Bongo','bongo',true),
('mazda','Tribute','tribute',true),
('mazda','Premacy','premacy',true),
('mazda','Demio','demio',true),
('mitsubishi','L200','l200',true),
('mitsubishi','Pajero','pajero',true),
('mitsubishi','Outlander','outlander',true),
('mitsubishi','ASX','asx',true),
('mitsubishi','Lancer','lancer',true),
('mitsubishi','Montero Sport','montero-sport',true),
('mitsubishi','Eclipse Cross','eclipse-cross',true),
('mitsubishi','Xpander','xpander',true),
('mitsubishi','Colt','colt',true),
('mitsubishi','Galant','galant',true),
('mitsubishi','Triton','triton',true),
('mitsubishi','Delica','delica',true),
('mitsubishi','Attrage','attrage',true),
('mitsubishi','Mirage','mirage',true),
('mitsubishi','Pajero Sport','pajero-sport',true),
('suzuki','Jimny','jimny',true),
('suzuki','Vitara','vitara',true),
('suzuki','Swift','swift',true),
('suzuki','Ertiga','ertiga',true),
('suzuki','Celerio','celerio',true),
('suzuki','Baleno','baleno',true),
('suzuki','Ignis','ignis',true),
('suzuki','S-Cross','s-cross',true),
('suzuki','Alto','alto',true),
('suzuki','Dzire','dzire',true),
('suzuki','XL7','xl7',true),
('suzuki','Carry','carry',true),
('suzuki','Wagon R','wagon-r',true),
('suzuki','Grand Vitara','grand-vitara',true),
('suzuki','Spresso','spresso',true),
('honda','CR-V','cr-v',true),
('honda','Civic','civic',true),
('honda','Accord','accord',true),
('honda','HR-V','hr-v',true),
('honda','Fit','fit',true),
('honda','City','city',true),
('honda','BR-V','br-v',true),
('honda','Pilot','pilot',true),
('honda','Odyssey','odyssey',true),
('honda','Jazz','jazz',true),
('honda','WR-V','wr-v',true),
('honda','Ridgeline','ridgeline',true),
('honda','CR-Z','cr-z',true),
('honda','Freed','freed',true),
('honda','Insight','insight',true),
('ford','Ranger','ranger',true),
('ford','Everest','everest',true),
('ford','Explorer','explorer',true),
('ford','Focus','focus',true),
('ford','F-150','f-150',true),
('ford','Escape','escape',true),
('ford','Edge','edge',true),
('ford','Expedition','expedition',true),
('ford','Mustang','mustang',true),
('ford','Bronco','bronco',true),
('ford','Transit','transit',true),
('ford','Fiesta','fiesta',true),
('ford','EcoSport','ecosport',true),
('ford','Maverick','maverick',true),
('ford','Territory','territory',true),
('chevrolet','Trailblazer','trailblazer',true),
('chevrolet','Captiva','captiva',true),
('chevrolet','Colorado','colorado',true),
('chevrolet','Spark','spark',true),
('chevrolet','Cruze','cruze',true),
('chevrolet','Equinox','equinox',true),
('chevrolet','Tahoe','tahoe',true),
('chevrolet','Suburban','suburban',true),
('chevrolet','S10','s10',true),
('chevrolet','Camaro','camaro',true),
('chevrolet','Onix','onix',true),
('chevrolet','Aveo','aveo',true),
('chevrolet','Tracker','tracker',true),
('chevrolet','Malibu','malibu',true),
('chevrolet','Traverse','traverse',true),
('volkswagen','Amarok','amarok',true),
('volkswagen','Golf','golf',true),
('volkswagen','Tiguan','tiguan',true),
('volkswagen','Passat','passat',true),
('volkswagen','Polo','polo',true),
('volkswagen','T-Cross','t-cross',true),
('volkswagen','Touareg','touareg',true),
('volkswagen','Jetta','jetta',true),
('volkswagen','Taos','taos',true),
('volkswagen','Atlas','atlas',true),
('volkswagen','Arteon','arteon',true),
('volkswagen','Caddy','caddy',true),
('volkswagen','Transporter','transporter',true),
('volkswagen','ID.4','id-4',true),
('volkswagen','Beetle','beetle',true),
('renault','Duster','duster-renault',true),
('renault','Clio','clio',true),
('renault','Megane','megane',true),
('renault','Kadjar','kadjar',true),
('renault','Kwid','kwid',true),
('renault','Captur','captur',true),
('renault','Logan','logan',true),
('renault','Sandero','sandero',true),
('renault','Koleos','koleos',true),
('renault','Fluence','fluence',true),
('renault','Kangoo','kangoo',true),
('renault','Master','master',true),
('renault','Talisman','talisman',true),
('renault','Scenic','scenic',true),
('renault','Arkana','arkana',true),
('peugeot','3008','3008',true),
('peugeot','2008','2008',true),
('peugeot','208','208',true),
('peugeot','308','308',true),
('peugeot','508','508',true),
('peugeot','5008','5008',true),
('peugeot','301','301',true),
('peugeot','406','406',true),
('peugeot','407','407',true),
('peugeot','Partner','partner',true),
('peugeot','Expert','expert',true),
('peugeot','Boxer','boxer',true),
('peugeot','408','408',true),
('peugeot','RCZ','rcz',true),
('peugeot','Traveller','traveller',true),
('dacia','Duster','duster-dacia',true),
('dacia','Logan','logan',true),
('dacia','Sandero','sandero',true),
('dacia','Dokker','dokker',true),
('dacia','Lodgy','lodgy',true),
('dacia','Spring','spring',true),
('dacia','Jogger','jogger',true),
('dacia','Stepway','stepway',true),
('dacia','Pick-Up','pick-up',true),
('dacia','Solenza','solenza',true),
('mercedes-benz','A-Class','a-class',true),
('mercedes-benz','B-Class','b-class',true),
('mercedes-benz','C-Class','c-class',true),
('mercedes-benz','CLA','cla',true),
('mercedes-benz','CLS','cls',true),
('mercedes-benz','E-Class','e-class',true),
('mercedes-benz','S-Class','s-class',true),
('mercedes-benz','GLA','gla',true),
('mercedes-benz','GLB','glb',true),
('mercedes-benz','GLC','glc',true),
('mercedes-benz','GLE','gle',true),
('mercedes-benz','GLS','gls',true),
('mercedes-benz','G-Class','g-class',true),
('mercedes-benz','V-Class','v-class',true),
('mercedes-benz','Sprinter','sprinter',true),
('bmw','1 Series','1-series',true),
('bmw','2 Series','2-series',true),
('bmw','3 Series','3-series',true),
('bmw','4 Series','4-series',true),
('bmw','5 Series','5-series',true),
('bmw','7 Series','7-series',true),
('bmw','X1','x1',true),
('bmw','X2','x2',true),
('bmw','X3','x3',true),
('bmw','X4','x4',true),
('bmw','X5','x5',true),
('bmw','X6','x6',true),
('bmw','X7','x7',true),
('bmw','i3','i3',true),
('bmw','iX','ix',true),
('audi','A1','a1',true),
('audi','A3','a3',true),
('audi','A4','a4',true),
('audi','A5','a5',true),
('audi','A6','a6',true),
('audi','A7','a7',true),
('audi','A8','a8',true),
('audi','Q2','q2',true),
('audi','Q3','q3',true),
('audi','Q5','q5',true),
('audi','Q7','q7',true),
('audi','Q8','q8',true),
('audi','TT','tt',true),
('audi','R8','r8',true),
('audi','e-tron','e-tron',true),
('isuzu','D-Max','d-max',true),
('isuzu','MU-X','mu-x',true),
('isuzu','N-Series','n-series',true),
('isuzu','F-Series','f-series',true),
('isuzu','Giga','giga',true),
('isuzu','Trooper','trooper',true),
('isuzu','Rodeo','rodeo',true),
('isuzu','Elf','elf',true),
('isuzu','Bighorn','bighorn',true),
('isuzu','Forward','forward',true),
('subaru','Forester','forester',true),
('subaru','Outback','outback',true),
('subaru','Impreza','impreza',true),
('subaru','XV','xv',true),
('subaru','Legacy','legacy',true),
('subaru','WRX','wrx',true),
('subaru','Levorg','levorg',true),
('subaru','BRZ','brz',true),
('subaru','Ascent','ascent',true),
('subaru','Crosstrek','crosstrek',true),
('land-rover','Defender','defender',true),
('land-rover','Discovery','discovery',true),
('land-rover','Discovery Sport','discovery-sport',true),
('land-rover','Range Rover','range-rover',true),
('land-rover','Range Rover Sport','range-rover-sport',true),
('land-rover','Range Rover Evoque','range-rover-evoque',true),
('land-rover','Range Rover Velar','range-rover-velar',true),
('land-rover','Freelander','freelander',true),
('land-rover','Series III','series-iii',true),
('land-rover','LR4','lr4',true),
('jac','T8','t8',true),
('jac','S3','s3',true),
('jac','S5','s5',true),
('jac','J7','j7',true),
('jac','N56','n56',true),
('jac','T6','t6',true),
('jac','X200','x200',true),
('jac','Sunray','sunray',true),
('jac','Refine S2','refine-s2',true),
('jac','iEV7S','iev7s',true),
('lexus','IS','is',true),
('lexus','ES','es',true),
('lexus','GS','gs',true),
('lexus','LS','ls',true),
('lexus','UX','ux',true),
('lexus','NX','nx',true),
('lexus','RX','rx',true),
('lexus','GX','gx',true),
('lexus','LX','lx',true),
('lexus','CT','ct',true),
('lexus','RC','rc',true),
('lexus','LC','lc',true),
('lexus','TX','tx',true),
('lexus','LM','lm',true),
('lexus','HS','hs',true),
('infiniti','Q30','q30',true),
('infiniti','Q50','q50',true),
('infiniti','Q60','q60',true),
('infiniti','QX50','qx50',true),
('infiniti','QX55','qx55',true),
('infiniti','QX60','qx60',true),
('infiniti','QX70','qx70',true),
('infiniti','QX80','qx80',true),
('infiniti','FX35','fx35',true),
('infiniti','G37','g37',true),
('porsche','911','911',true),
('porsche','718 Cayman','718-cayman',true),
('porsche','718 Boxster','718-boxster',true),
('porsche','Panamera','panamera',true),
('porsche','Macan','macan',true),
('porsche','Cayenne','cayenne',true),
('porsche','Taycan','taycan',true),
('porsche','Cayman GT4','cayman-gt4',true),
('porsche','Carrera GT','carrera-gt',true),
('porsche','918 Spyder','918-spyder',true),
('mini','3 Door','3-door',true),
('mini','5 Door','5-door',true),
('mini','Clubman','clubman',true),
('mini','Countryman','countryman',true),
('mini','Convertible','convertible',true),
('mini','Paceman','paceman',true),
('mini','Coupe','coupe',true),
('mini','Roadster','roadster',true),
('mini','Aceman','aceman',true),
('mini','Electric','electric',true),
('jeep','Wrangler','wrangler',true),
('jeep','Grand Cherokee','grand-cherokee',true),
('jeep','Cherokee','cherokee',true),
('jeep','Compass','compass',true),
('jeep','Renegade','renegade',true),
('jeep','Gladiator','gladiator',true),
('jeep','Patriot','patriot',true),
('jeep','Liberty','liberty',true),
('jeep','Wagoneer','wagoneer',true),
('jeep','Commander','commander',true),
('ram','1500','1500',true),
('ram','2500','2500',true),
('ram','3500','3500',true),
('ram','ProMaster','promaster',true),
('ram','ProMaster City','promaster-city',true),
('ram','TRX','trx',true),
('ram','Rebel','rebel',true),
('ram','Laramie','laramie',true),
('ram','Limited','limited',true),
('ram','Classic','classic',true),
('volvo','S60','s60',true),
('volvo','S90','s90',true),
('volvo','V60','v60',true),
('volvo','V90','v90',true),
('volvo','XC40','xc40',true),
('volvo','XC60','xc60',true),
('volvo','XC90','xc90',true),
('volvo','C40','c40',true),
('volvo','EX30','ex30',true),
('volvo','EX90','ex90',true),
('skoda','Fabia','fabia',true),
('skoda','Octavia','octavia',true),
('skoda','Superb','superb',true),
('skoda','Rapid','rapid',true),
('skoda','Scala','scala',true),
('skoda','Kamiq','kamiq',true),
('skoda','Karoq','karoq',true),
('skoda','Kodiaq','kodiaq',true),
('skoda','Enyaq','enyaq',true),
('skoda','Yeti','yeti',true),
('seat','Ibiza','ibiza',true),
('seat','Leon','leon',true),
('seat','Toledo','toledo',true),
('seat','Ateca','ateca',true),
('seat','Arona','arona',true),
('seat','Tarraco','tarraco',true),
('seat','Alhambra','alhambra',true),
('seat','Mii','mii',true),
('seat','Cordoba','cordoba',true),
('seat','Exeo','exeo',true),
('cupra','Formentor','formentor',true),
('cupra','Leon','leon',true),
('cupra','Ateca','ateca',true),
('cupra','Born','born',true),
('cupra','Tavascan','tavascan',true),
('cupra','Terramar','terramar',true),
('citroen','C1','c1',true),
('citroen','C3','c3',true),
('citroen','C4','c4',true),
('citroen','C5','c5',true),
('citroen','C5 Aircross','c5-aircross',true),
('citroen','Berlingo','berlingo',true),
('citroen','Jumpy','jumpy',true),
('citroen','Jumper','jumper',true),
('citroen','DS3','ds3',true),
('citroen','Saxo','saxo',true),
('opel','Corsa','corsa',true),
('opel','Astra','astra',true),
('opel','Insignia','insignia',true),
('opel','Mokka','mokka',true),
('opel','Grandland','grandland',true),
('opel','Crossland','crossland',true),
('opel','Zafira','zafira',true),
('opel','Combo','combo',true),
('opel','Vivaro','vivaro',true),
('opel','Movano','movano',true),
('fiat','500','500',true),
('fiat','Panda','panda',true),
('fiat','Punto','punto',true),
('fiat','Tipo','tipo',true),
('fiat','Linea','linea',true),
('fiat','Doblo','doblo',true),
('fiat','Ducato','ducato',true),
('fiat','Fiorino','fiorino',true),
('fiat','Toro','toro',true),
('fiat','Strada','strada',true),
('alfa-romeo','Giulia','giulia',true),
('alfa-romeo','Stelvio','stelvio',true),
('alfa-romeo','Giulietta','giulietta',true),
('alfa-romeo','Tonale','tonale',true),
('alfa-romeo','159','159',true),
('alfa-romeo','Brera','brera',true),
('alfa-romeo','Spider','spider',true),
('alfa-romeo','Mito','mito',true),
('alfa-romeo','4C','4c',true),
('alfa-romeo','156','156',true),
('chery','Tiggo 2','tiggo-2',true),
('chery','Tiggo 3','tiggo-3',true),
('chery','Tiggo 4','tiggo-4',true),
('chery','Tiggo 5','tiggo-5',true),
('chery','Tiggo 7','tiggo-7',true),
('chery','Tiggo 8','tiggo-8',true),
('chery','Arrizo 5','arrizo-5',true),
('chery','Arrizo 6','arrizo-6',true),
('chery','QQ','qq',true),
('chery','Fulwin','fulwin',true),
('geely','Coolray','coolray',true),
('geely','Emgrand','emgrand',true),
('geely','Atlas','atlas',true),
('geely','Okavango','okavango',true),
('geely','Geometry C','geometry-c',true),
('geely','Panda','panda',true),
('geely','GX3','gx3',true),
('geely','Preface','preface',true),
('geely','Monjaro','monjaro',true),
('geely','Azkarra','azkarra',true),
('byd','Atto 3','atto-3',true),
('byd','Han','han',true),
('byd','Tang','tang',true),
('byd','Dolphin','dolphin',true),
('byd','Seal','seal',true),
('byd','Song Plus','song-plus',true),
('byd','Yuan Plus','yuan-plus',true),
('byd','Qin Plus','qin-plus',true),
('byd','Destroyer 05','destroyer-05',true),
('byd','e2','e2',true),
('great-wall','Wingle 5','wingle-5',true),
('great-wall','Wingle 7','wingle-7',true),
('great-wall','Poer','poer',true),
('great-wall','Steed','steed',true),
('great-wall','Cannon','cannon',true),
('great-wall','Haval H5','haval-h5',true),
('great-wall','Voleex C30','voleex-c30',true),
('great-wall','Peri','peri',true),
('great-wall','Florid','florid',true),
('great-wall','Hover','hover',true),
('haval','H1','h1',true),
('haval','H2','h2',true),
('haval','H4','h4',true),
('haval','H5','h5',true),
('haval','H6','h6',true),
('haval','H7','h7',true),
('haval','H9','h9',true),
('haval','Jolion','jolion',true),
('haval','M6','m6',true),
('haval','Dargo','dargo',true),
('mg','MG3','mg3',true),
('mg','MG5','mg5',true),
('mg','MG6','mg6',true),
('mg','MG ZS','mg-zs',true),
('mg','MG HS','mg-hs',true),
('mg','MG One','mg-one',true),
('mg','MG4','mg4',true),
('mg','MG7','mg7',true),
('mg','Cyberster','cyberster',true),
('mg','RX5','rx5',true),
('tesla','Model S','model-s',true),
('tesla','Model 3','model-3',true),
('tesla','Model X','model-x',true),
('tesla','Model Y','model-y',true),
('tesla','Cybertruck','cybertruck',true),
('tesla','Roadster','roadster',true),
('polestar','Polestar 1','polestar-1',true),
('polestar','Polestar 2','polestar-2',true),
('polestar','Polestar 3','polestar-3',true),
('polestar','Polestar 4','polestar-4',true),
('jaguar','XE','xe',true),
('jaguar','XF','xf',true),
('jaguar','XJ','xj',true),
('jaguar','F-Type','f-type',true),
('jaguar','F-Pace','f-pace',true),
('jaguar','E-Pace','e-pace',true),
('jaguar','I-Pace','i-pace',true),
('jaguar','XK','xk',true),
('jaguar','S-Type','s-type',true),
('jaguar','X-Type','x-type',true),
('maserati','Ghibli','ghibli',true),
('maserati','Quattroporte','quattroporte',true),
('maserati','Levante','levante',true),
('maserati','Grecale','grecale',true),
('maserati','GranTurismo','granturismo',true),
('maserati','GranCabrio','grancabrio',true),
('maserati','MC20','mc20',true),
('maserati','Spyder','spyder',true),
('ferrari','458','458',true),
('ferrari','488','488',true),
('ferrari','F8','f8',true),
('ferrari','Portofino','portofino',true),
('ferrari','Roma','roma',true),
('ferrari','SF90','sf90',true),
('ferrari','296 GTB','296-gtb',true),
('ferrari','812 Superfast','812-superfast',true),
('ferrari','LaFerrari','laferrari',true),
('ferrari','California','california',true),
('lamborghini','Gallardo','gallardo',true),
('lamborghini','Huracan','huracan',true),
('lamborghini','Aventador','aventador',true),
('lamborghini','Urus','urus',true),
('lamborghini','Murcielago','murcielago',true),
('lamborghini','Revuelto','revuelto',true),
('lamborghini','Diablo','diablo',true),
('lamborghini','Countach','countach',true),
('bentley','Continental GT','continental-gt',true),
('bentley','Flying Spur','flying-spur',true),
('bentley','Bentayga','bentayga',true),
('bentley','Mulsanne','mulsanne',true),
('bentley','Azure','azure',true),
('bentley','Arnage','arnage',true),
('rolls-royce','Phantom','phantom',true),
('rolls-royce','Ghost','ghost',true),
('rolls-royce','Wraith','wraith',true),
('rolls-royce','Dawn','dawn',true),
('rolls-royce','Cullinan','cullinan',true),
('rolls-royce','Spectre','spectre',true),
('aston-martin','Vantage','vantage',true),
('aston-martin','DB11','db11',true),
('aston-martin','DB12','db12',true),
('aston-martin','DBS','dbs',true),
('aston-martin','DBX','dbx',true),
('aston-martin','Rapide','rapide',true),
('aston-martin','Vanquish','vanquish',true),
('bugatti','Veyron','veyron',true),
('bugatti','Chiron','chiron',true),
('bugatti','Divo','divo',true),
('bugatti','Bolide','bolide',true),
('bugatti','Mistral','mistral',true),
('ds','DS 3','ds-3',true),
('ds','DS 4','ds-4',true),
('ds','DS 5','ds-5',true),
('ds','DS 7','ds-7',true),
('ds','DS 9','ds-9',true),
('saic','Maxus T60','maxus-t60',true),
('saic','Maxus V80','maxus-v80',true),
('saic','Maxus G10','maxus-g10',true),
('saic','Roewe RX5','roewe-rx5',true),
('saic','Roewe i5','roewe-i5',true),
('saic','MG6','mg6',true),
('saic','LDV T60','ldv-t60',true);
INSERT INTO models ("Id", "BrandId", "Name", "Slug", "IsActive")
SELECT
  (
    substr(md5(tm.brand_slug || ':' || tm.slug),1,8) || '-' ||
    substr(md5(tm.brand_slug || ':' || tm.slug),9,4) || '-' ||
    substr(md5(tm.brand_slug || ':' || tm.slug),13,4) || '-' ||
    substr(md5(tm.brand_slug || ':' || tm.slug),17,4) || '-' ||
    substr(md5(tm.brand_slug || ':' || tm.slug),21,12)
  )::uuid,
  b."Id",
  tm.name,
  tm.slug,
  tm.is_active
FROM tmp_models tm
INNER JOIN brands b ON b."Slug" = tm.brand_slug
ON CONFLICT ("BrandId", "Slug") DO UPDATE
SET "Name" = EXCLUDED."Name",
    "IsActive" = EXCLUDED."IsActive";
